name:             GameStage Expo // 24.–26. September
markdown:         redcarpet
pygments:         false
exclude:          [
					'LICENSE',
					'README.md',
                    '.sass-cache',
                    'node_modules',
                    'scss',
                    'Gruntfile.js',
                    'package.json',
                    '*.sublime-project',
                    '*.sublime-workspace',
                    '*.bat',
                    '*.map',
                    '*.zip'
                  ]