name:     GameStage Expo / 12.–14. September / Tabakfabrik Linz
markdown: redcarpet
pygments: false
exclude:  [
            'LICENSE',
            'README.md',
            'scss',
            'Gruntfile.js',
            'package.json',
          ]
